### ISSUE TITLE
关系抽取中的实体lable

### ISSUE THREAD

**Issue by gao929165733** [NLPxiaoxu/Entity-recognition-and-Relation-ectraction#1]
输入只是句子向量，实体标签好像没有作为输入，那标签信息是怎么包含在输入中的

**Comment by X-jun-0130** [comment]
你是指label embedding嘛, 这个放在model_er里面作为输入了。但其实一般实体标签会是B-loc, B-per；loc表示地点实体，per表示人之类的。
我写的程序里面，我简化了，实体只是单纯的B,I这样，没有包含太多的实体类型信息。
在论文中，作者将label embedding和bilstm输出进行最后一维拼接， 但在拼接之前，给label embedding做了一个权重W处理，我忘记具体的做法了.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"gao929165733"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月27日(星期三) 下午4:36
收件人:&nbsp;"NLPxiaoxu/Entity-recognition-and-Relation-ectraction"<Entity-recognition-and-Relation-ectraction@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[NLPxiaoxu/Entity-recognition-and-Relation-ectraction] 关系抽取中的实体lable (#1)





 
输入只是句子向量，实体标签好像没有作为输入，那标签信息是怎么包含在输入中的

**Comment by gao929165733** [comment]
我指的是你的单独的关系抽取部分，不是联合抽取哈

**Comment by X-jun-0130** [comment]
关系抽取里面并没有用到实体标签信息
这部分只是预测关系矩阵；
可以认为网络在学习关系矩阵时，从句子中学到了跟实体有关的知识

**Comment by gao929165733** [comment]
好的 感谢！

**Comment by gao929165733** [comment]
你好，我又来打扰了，请问left和right两个网络层以及它们进行broadcasting的目的是什么呢？

**Comment by X-jun-0130** [comment]
左右两个进行维度上拼接，left=[16,128,100], right=[16,128,100]; broadcasting后[16,128,128,100]
处理后的数据，是关系识别需要的，因为网络中关系矩阵是4维的
