### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by JackeyGuo** [NLPxiaoxu/Entity-recognition-and-Relation-ectraction#2]
你好，谢谢您提供的代码，我看到您在readme中模型一里说“使用字向量，首先制作字典，选取前4996个字”，在代码里没有看到呢，能解释一下吗？而且我用模型一在自己的数据集，跑出来F1值为0.

**Comment by X-jun-0130** [comment]
这部分其实就是根据字频取前4996个；
字典我保存下来了word2id.txt，在data文件中,解压就能看到，代码我没放进去；
使用自己的数据集，可以根据文档，自己重新建立一个字典，替换word2id.txt就好；
使用我提供的字典的话，如果您的文档与字典字符相差比较大的话，模型可能没结果的
